# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c22a958e90d20d335c76b4bc628bd7bd029f03e7e4da83ae7f4070878921895da4c47fa3fb3435d9cd9d774e393148f40f4a7abbdfa78b50e0764663fae9869f

test:
  secret_key_base: 9cffb41d46ffff14475862b39bf32fb42224f0313833bed11d4ec7b77e0d420b09dcaaac983e8ae680af676d77d0fad2649dfaf5baf15c46927d27fa5d3795e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
